### ISSUE TITLE
invalid characters in font family

### ISSUE THREAD

**Issue by imahdio** [imahdio/CSS-Essential-Training#15]
I'm studying Changing the font-family lesson from [here](http://168.119.85.43/css-essential-training-3/05-Typography/)
 in last seconds of that lesson , instructor said:

>One more thing to note about font-family names. If they contain numbers or characters, other than a hyphen these characters must be escaped by adding a backslash before the invalid character.

based on it
why Jersey M54 font , not have any backslash in front of its number [in here](https://www.cdnfonts.com/jersey-m54.font)?
```css
font-family: 'Jersey M54', sans-serif;
```

as well as font exo 2 [in here](https://stackoverflow.com/questions/67570043/font-weight-issue-with-font-exo-2-on-firefox?noredirect=1&lq=1)
```css
font-family: 'Exo 2';
```

**Comment by sharmag44** [comment]
if a font-family name contains multiple words, separated by spaces, it is recommended to list the family name in quotation marks (single or double)
and 
i think sans-serif is old font-family that's by it use a hypen instead of space

**Comment by Tamhat** [comment]
Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means that punctuation characters and digits at the start of each token must be escaped in unquoted font family names.
If you use quotes
This will work even if you use numbers in the font-family


![image](https://user-images.githubusercontent.com/87254817/149502082-3d52d1df-5bd7-4154-9e37-874894f3dcfa.png)
